all: html

SPHINX_PROJECT_NAME = A16 sliceKIT Ethernet sleep wake combo demo quickstart guide
VERSION = 1.0
SOURCE_INCLUDE_DIRS = ../../app_a16_slicekit_ethernet_sleep_wake_combo_demo
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
